sudo: required

language: c

services:
  - docker

before_install:
  - docker info
  - docker build -t jousby/simple-buildbox .

script:
  - docker run -it --entrypoint "/bin/bash" jousby/simple-buildbox -c "source /opt/sdkman/bin/sdkman-init.sh && java -version"